name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: webcardinal-workspace_node-modules
        with:
          path: ./webcardinal-workspace/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./webcardinal-workspace/package-lock.json') }}-v2

      - name: Install
        run: npm install && npm run clean
        shell: bash

      - name: Latest WebCardinal
        run: npm run get-source-code
        shell: bash

      - name: Release
        run: npm run release
        shell: bash

      - name: Archive
        run: zip -q -r webcardinal-release.zip ./dist
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: webcardinal-release
          path: webcardinal-release.zip